export const products = [
  {
    id: 1,
    name: "Sakura Ceramic Tea Set",
    price: 45.99,
    country: "Japan",
    rating: 4.8,
    quantity: 32,
    image: "https://picsum.photos/seed/product1/300/200",
  },
  {
    id: 2,
    name: "Organic Honey Jar",
    price: 18.5,
    country: "Bangladesh",
    rating: 4.6,
    quantity: 54,
    image: "https://picsum.photos/seed/product2/300/200",
  },
  {
    id: 3,
    name: "Leather Travel Wallet",
    price: 59.0,
    country: "Italy",
    rating: 4.7,
    quantity: 21,
    image: "https://picsum.photos/seed/product3/300/200",
  },
  {
    id: 4,
    name: "Bamboo Cutting Board Set",
    price: 34.25,
    country: "China",
    rating: 4.4,
    quantity: 67,
    image: "https://picsum.photos/seed/product4/300/200",
  },
  {
    id: 5,
    name: "Wireless Bluetooth Earbuds",
    price: 79.99,
    country: "USA",
    rating: 4.5,
    quantity: 45,
    image: "https://picsum.photos/seed/product5/300/200",
  },
  {
    id: 6,
    name: "Handmade Wool Scarf",
    price: 29.5,
    country: "Nepal",
    rating: 4.9,
    quantity: 38,
    image: "https://picsum.photos/seed/product6/300/200",
  },
  {
    id: 7,
    name: "Premium Coffee Beans 1kg",
    price: 24.99,
    country: "Brazil",
    rating: 4.7,
    quantity: 60,
    image: "https://picsum.photos/seed/product7/300/200",
  },
  {
    id: 8,
    name: "Nordic Minimalist Lamp",
    price: 64.75,
    country: "Sweden",
    rating: 4.3,
    quantity: 29,
    image: "https://picsum.photos/seed/product8/300/200",
  },
  {
    id: 9,
    name: "Smart Fitness Tracker",
    price: 89.99,
    country: "Germany",
    rating: 4.6,
    quantity: 50,
    image: "https://picsum.photos/seed/product9/300/200",
  },
  {
    id: 10,
    name: "Recycled Cotton Tote Bag",
    price: 22.0,
    country: "India",
    rating: 4.5,
    quantity: 73,
    image: "https://picsum.photos/seed/product10/300/200",
  },
  {
    id: 11,
    name: "Aromatic Candle Pack",
    price: 27.5,
    country: "France",
    rating: 4.8,
    quantity: 41,
    image: "https://picsum.photos/seed/product11/300/200",
  },
  {
    id: 12,
    name: "Handcrafted Clay Vase",
    price: 39.99,
    country: "Turkey",
    rating: 4.4,
    quantity: 18,
    image: "https://picsum.photos/seed/product12/300/200",
  },
  {
    id: 13,
    name: "Natural Shea Butter Cream",
    price: 19.75,
    country: "Ghana",
    rating: 4.9,
    quantity: 46,
    image: "https://picsum.photos/seed/product13/300/200",
  },
  {
    id: 14,
    name: "Portable Mini Speaker",
    price: 34.0,
    country: "South Korea",
    rating: 4.5,
    quantity: 58,
    image: "https://picsum.photos/seed/product14/300/200",
  },
  {
    id: 15,
    name: "Wooden Chess Set",
    price: 48.25,
    country: "Poland",
    rating: 4.6,
    quantity: 22,
    image: "https://picsum.photos/seed/product15/300/200",
  },
  {
    id: 16,
    name: "Eco-Friendly Water Bottle",
    price: 16.5,
    country: "Thailand",
    rating: 4.4,
    quantity: 75,
    image: "https://picsum.photos/seed/product16/300/200",
  },
  {
    id: 17,
    name: "Wireless Gaming Mouse",
    price: 52.99,
    country: "USA",
    rating: 4.7,
    quantity: 30,
    image: "https://picsum.photos/seed/product17/300/200",
  },
  {
    id: 18,
    name: "Silk Pillow Cover Set",
    price: 36.9,
    country: "Vietnam",
    rating: 4.8,
    quantity: 44,
    image: "https://picsum.photos/seed/product18/300/200",
  },
  {
    id: 19,
    name: "Smart Home Plug",
    price: 29.0,
    country: "UK",
    rating: 4.3,
    quantity: 66,
    image: "https://picsum.photos/seed/product19/300/200",
  },
  {
    id: 20,
    name: "Mountain Explorer Backpack",
    price: 95.0,
    country: "Canada",
    rating: 4.9,
    quantity: 25,
    image: "https://picsum.photos/seed/product20/300/200",
  },
];
